export { Card } from './Card'
export { Footer } from './Footer'
export { TheOcean } from './TheOcean'
export { Title } from './Title'
export { Sardine } from './Sardine'
export { Detail } from './Detail'
